export const ACTIONS = {
  SEARCH_SKILLS_REQUEST: 'SEARCH_SKILLS_REQUEST',
  SEARCH_SKILLS_FAILURE: 'SEARCH_SKILLS_FAILURE',
  SEARCH_SKILLS_SUCCESS: 'SEARCH_SKILLS_SUCCESS',
  CHANGE_SEARCH_FIELD: 'CHANGE_SEARCH_FIELD'
};